### PR TITLE
support unpresuf

### PR DESCRIPTION
**Pull request by yury-egorenkov**
Untitled

### CODE REVIEW

**Comment by mitranim** [comment]
Looks nice. Gif demonstration is pretty cool. Maybe `misc_unwrap`?

**Comment by mitranim** [comment]
Not sure if this would work for regions shorter than 2 characters.

**Comment by yury-egorenkov** [comment]
> Looks nice. Gif demonstration is pretty cool. Maybe `misc_unwrap`?

It not only `unwrap`, it doesn't rely on what characters are, just remove the first and last char. So I think this name is more precise.

> Not sure if this would work for regions shorter than 2 characters.

It just will remove a selected character.

**Comment by mitranim** [comment]
"Prefix" and "suffix" usually imply specific strings for prefix and suffix. Maybe `misc_unwrap1`?

**Comment by yury-egorenkov** [comment]
Pushed

**Pull request merged**
